import type { ProjectTask } from './task.types'

export const PROJECT_TASKS: ProjectTask[] = [
  {
    taskId: 1,
    projId: 1,
    taskTypeCd: '01',
    taskScopeCd: '01',
    taskMngrId: 1022,
    taskMngrName: '김민준',
    taskStatCd: '00',
    taskPriorityCd: '01',
    taskNm: '결제 게이트웨이 UI 컴포넌트 개발',
    taskCn: '글로벌 결제 승인 화면에서 사용할 공통 입력, 상태 표시, 오류 안내 컴포넌트를 구현합니다.',
    taskBgngDt: '2025-07-01',
    taskEndDt: '2025-07-10',
    taskProgressRate: 0,
  },
  {
    taskId: 2,
    projId: 1,
    taskTypeCd: '01',
    taskScopeCd: '01',
    taskMngrId: 1031,
    taskMngrName: '이보라',
    taskStatCd: '00',
    taskPriorityCd: '02',
    taskNm: '결제 이력 테이블 인덱스 최적화',
    taskCn: '정산 목록 조회 속도 개선을 위해 결제일, 거래 상태, 사용자 기준 복합 인덱스를 검토합니다.',
    taskBgngDt: '2025-07-03',
    taskEndDt: '2025-07-15',
    taskProgressRate: 0,
  },
  {
    taskId: 3,
    projId: 1,
    taskTypeCd: '03',
    taskScopeCd: '01',
    taskMngrId: 1014,
    taskMngrName: '박다은',
    taskStatCd: '00',
    taskPriorityCd: '03',
    taskNm: '다국어 결제 UI 문구 정리',
    taskCn: '한국어, 영어, 일본어 결제 화면 문구를 정리하고 번역 요청 목록을 문서화합니다.',
    taskBgngDt: '2025-07-08',
    taskEndDt: '2025-07-20',
    taskProgressRate: 0,
  },
  {
    taskId: 4,
    projId: 1,
    taskTypeCd: '01',
    taskScopeCd: '01',
    taskMngrId: 1031,
    taskMngrName: '이보라',
    taskStatCd: '01',
    taskPriorityCd: '01',
    taskNm: 'PG사 연동 API 서버 구현',
    taskCn: '외부 PG 승인, 취소, 환불 API 연동을 위한 서버 모듈과 예외 처리 흐름을 구현합니다.',
    taskBgngDt: '2025-07-01',
    taskEndDt: '2025-07-08',
    taskProgressRate: 65,
  },
  {
    taskId: 5,
    projId: 1,
    taskTypeCd: '01',
    taskScopeCd: '01',
    taskMngrId: 1048,
    taskMngrName: '최인호',
    taskStatCd: '01',
    taskPriorityCd: '02',
    taskNm: '결제 서버 Redis 캐시 레이어 구성',
    taskCn: '환율과 수수료 정책 조회 성능 개선을 위해 Redis 캐시 키 설계와 만료 정책을 구성합니다.',
    taskBgngDt: '2025-07-02',
    taskEndDt: '2025-07-12',
    taskProgressRate: 40,
  },
  {
    taskId: 6,
    projId: 1,
    taskTypeCd: '02',
    taskScopeCd: '01',
    taskMngrId: 1048,
    taskMngrName: '최인호',
    taskStatCd: '03',
    taskPriorityCd: '01',
    taskNm: '환불 처리 로직 검증',
    taskCn: '부분 환불과 전체 환불 케이스 검증 중 외부 PG 테스트 서버 응답 지연으로 일시중지되었습니다.',
    taskBgngDt: '2025-07-03',
    taskEndDt: '2025-07-05',
    taskProgressRate: 80,
  },
  {
    taskId: 7,
    projId: 1,
    taskTypeCd: '02',
    taskScopeCd: '01',
    taskMngrId: 1022,
    taskMngrName: '김민준',
    taskStatCd: '02',
    taskPriorityCd: '02',
    taskNm: '결제 완료 페이지 반응형 검수',
    taskCn: '모바일, 태블릿, 데스크톱 해상도에서 결제 완료 페이지의 레이아웃을 검수했습니다.',
    taskBgngDt: '2025-06-28',
    taskEndDt: '2025-07-06',
    taskProgressRate: 100,
  },
  {
    taskId: 8,
    projId: null,
    taskTypeCd: '05',
    taskScopeCd: '02',
    taskMngrId: 1031,
    taskMngrName: '이보라',
    taskStatCd: '02',
    taskPriorityCd: '03',
    taskNm: '주간 업무 보고 작성',
    taskCn: '이번 주 프로젝트 진행 상황과 이슈 사항을 정리해 주간 보고 문서를 작성했습니다.',
    taskBgngDt: '2025-06-27',
    taskEndDt: '2025-06-30',
    taskProgressRate: 100,
  },
]
